/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#000000",
              "primary-container": "#cc80fd",
              "on-error-container": "#510017",
              "on-surface": "#2d2f2f",
              "on-primary-container": "#3a005b",
              "primary-fixed": "#cc80fd",
              "on-surface-variant": "#5a5c5c",
              "secondary-fixed-dim": "#ffb467",
              "inverse-on-surface": "#9c9d9d",
              "inverse-surface": "#0c0f0f",
              "error-dim": "#a70138",
              "on-tertiary-fixed-variant": "#6d6d6d",
              "on-background": "#2d2f2f",
              "surface-tint": "#8137b1",
              "tertiary-container": "#ffffff",
              "on-tertiary-container": "#626262",
              "error-container": "#f74b6d",
              "surface-container-highest": "#dbdddd",
              "on-primary-fixed-variant": "#48006f",
              "primary": "#8137b1",
              "surface-container-low": "#f0f1f1",
              "secondary-fixed": "#ffc791",
              "on-tertiary": "#f3f3f3",
              "tertiary-fixed-dim": "#f1f1f1",
              "background": "#f6f6f6",
              "surface-container-lowest": "#ffffff",
              "secondary-dim": "#764400",
              "secondary": "#874e00",
              "on-secondary-fixed-variant": "#774400",
              "primary-dim": "#7428a4",
              "tertiary": "#5b5b5b",
              "outline-variant": "#acadad",
              "tertiary-dim": "#4f4f4f",
              "on-tertiary-fixed": "#505050",
              "on-primary": "#fdeeff",
              "surface": "#f6f6f6",
              "tertiary-fixed": "#ffffff",
              "error": "#b41340",
              "surface-bright": "#f6f6f6",
              "on-secondary-container": "#6a3c00",
              "primary-fixed-dim": "#be72ef",
              "on-error": "#ffefef",
              "inverse-primary": "#c77af7",
              "surface-container": "#e7e8e8",
              "surface-dim": "#d3d5d5",
              "surface-variant": "#dbdddd",
              "outline": "#767777",
              "on-secondary": "#fff0e5",
              "secondary-container": "#ffc791",
              "on-secondary-fixed": "#4f2c00",
              "surface-container-high": "#e1e3e3"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Plus Jakarta Sans"],
              "display": ["Plus Jakarta Sans"],
              "body": ["Manrope"],
              "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
